export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
